language: python
cache: pip
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install .
script:
  - black --check .
  - pytest
deploy:
  provider: pypi
  user: $PYPIUSER
  password: $PYPIPASSWORD
  on:
    python: "3.6"
    tags: true
